### ISSUE TITLE
Doesn't work with Ember 2.16

### ISSUE THREAD

**Issue by GendelfLugansk** [brzpegasus/ember-cli-nwjs#68]
I used this addon with Ember 2.8 and everything worked. Today I tried to update to recent ember version and faced "Cannot find module app-name/routes/application" error in console. Spent few hours trying to debug it. I think it's caused by recent babel versions and new ember imports. Found a workaround: use `requireNode` for node modules. Example: `fs = requireNode('fs')`  instead of `fs = require('fs')`.
